<head>
  <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">
</head>
<body>
  <div style="background-color: black; color: white; padding: 20px; border-radius: 8px; font-family: 'Press Start 2P', Arial, sans-serif;">
    <h3>Echo Shift</h3>
    <h1>Welcome to Echo Shift Bug Fixes! Its a place where you can go if you find bugs in the game. So check below for a list of bug fixes</h1>
    <p>Player not inside the map or seeing another camera?</p>
    <p>Leave the lobby and join back</p>
    <p>Not being able to play and still stuck in the menu?</p>
    <p>Leave and make your own lobby</p>
    <h3>If there is anymore bugs, comment it on the itch.io page and i will fix it!</h3>
  </div>
</body>
